### ISSUE TITLE
Uncaught error when trying to access dashboard

### ISSUE THREAD

**Issue by jacmaes** [gadgetto/SnipWire#1]
Everything seems to be running smoothly, I have installed the Snipcart product package, can add the products to the cart and proceed to checkout. But when I try to access the SnipWire dashboard, I get the following error: 

Fatal Error: Uncaught Error: Call to a member function getProducts() on null in /var/www/vhosts/xxx/site/modules/SnipWire/services/SnipREST.php:304

Mode: Test mode
SnipWire version: 0.6 (latest)
PW version: 3.0.149 dev

**Comment by gadgetto** [comment]
I have pushed a fix for this! Thanks for your report!
You run into it because your server doesn't have cURL support enabled.

I would strongly recommend you enable cURL in your environment, otherwise the SnipWire dashboard will respond very slow. SnipWire uses paralleled multi cURL to query the Snipcart REST API.

Could you please test if the fix works and close the issue?

**Comment by jacmaes** [comment]
I do have cURL enabled, from what I gather (see the two sreenshots). My server is running the latest version of Plesk with PHP 7.4.1. I'm going to update your module to see if the issue is fixed, and will let you know. 
![terminal](https://user-images.githubusercontent.com/1206842/72816040-dd47f500-3c67-11ea-803e-125f0935ade2.png)
![phpinfo](https://user-images.githubusercontent.com/1206842/72816041-dde08b80-3c67-11ea-9f9d-5216fc42ec3b.png)

**Comment by jacmaes** [comment]
Sorry to report that after updating the module and doing a Modules > Refresh, I'm still seeing an error, although on a different line:
`Fatal Error: Uncaught Error: Call to a member function getOrders() on null in /var/www/vhosts/xxx/httpdocs/dev/site/modules/SnipWire/services/SnipREST.php:314
Stack trace:
#0 /var/www/vhosts/xxx/httpdocs/dev/site/modules/SnipWire/services/SnipREST.php(159): ProcessWire\SnipREST->_getDashboardDataSingle()
#1 /var/www/vhosts/xxx/httpdocs/dev/site/modules/SnipWire/ProcessSnipWire/sections/Dashboard.php(61): ProcessWire\SnipREST->getDashboardData()
#2 /var/www/vhosts/xxx/httpdocs/dev/wire/core/Wire.php(380): ProcessWire\ProcessSnipWire->___execute()
#3 /var/www/vhosts/xxx/httpdocs/dev/wire/core/WireHooks.php(823): ProcessWire\Wire->_callMethod()
#4 /var/www/vhosts/xxx/httpdocs/dev/wire/core/Wire.php(450): ProcessWire\WireHooks->runHooks()
#5 /var/www/vhosts/xxx/httpdocs/dev/wire/core/ProcessController.php(337): ProcessWire\Wire->__call()
#6 /var/www/vhosts/xxx/httpdocs/dev/wire/core/Wire.php(380): ProcessWire\Proces (line 314 of /var/www/vhosts/xxx/httpdocs/dev/site/modules/SnipWire/services/SnipREST.php) `

**Comment by gadgetto** [comment]
**Regarding your error message** - I pushed another fix! Sorry I still had a stupid typo in code.
Please use new package from GitHub.

**The other problem** - your PW installation doesn't seem to recognize the cURL support from your server. In this case SnipWire switches to a much slower fallback mode and uses fopen to fetch data from Snipcarts REST API (instead of paralleled multi cURL).

The following line in ProcessWires WireHttp class checks for cURL support:
```php
$this->hasCURL = function_exists('curl_init') && !ini_get('safe_mode') && !ini_get('open_basedir');
```
So you need cURL support in PHP + safe_mode disabled + open_basedir disabled

**Comment by gadgetto** [comment]
From a StackOverflow thread:

https://stackoverflow.com/questions/19539922/php-can-curlopt-followlocation-and-open-basedir-be-used-together

> The answer appears to be, "no you can't do that". The CURLOPT_FOLLOWLOCATION option on PHP curl (curl_setopt) and the open_basedir option in php.ini are basically incompatible, and there is no programmatical way to make them work together.

**Comment by jacmaes** [comment]
Disabling open_basedir in Plesk was sufficient to make it work. Thanks for the tip!

**Comment by gadgetto** [comment]
Great! And thanks for your bug report!
